<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "seo_basics_plugin_sitemap"
 *
 * Auto generated by Extension Builder 2014-01-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SEO Basics Sitemap for Plugins',
	'description' => '',
	'category' => 'fe',
	'author' => 'Henrik Braune',
	'author_email' => 'henrik@braune.org',
	'author_company' => 'HENRIK BRAUNE',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.6.0-6.1.99',
			'extbase' => '1.3',
			'fluid' => '1.3',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>